version: 0.0.{build}

install:
- cmd: >-
    SET PYTHON=C:\\Python27

    SET PYTHONUSERBASE=C:\\Projects\\railwoks-dsd\\venv

    SET PATH=%PYTHONUSERBASE%\\Scripts;%PYTHON%;%PYTHON%\\Scripts;%PATH%

    pip install --user -U pip setuptools

    pip install --user -r requirements.txt -r test_requirements.txt

build: off

test_script:
- cmd: nosetests.exe
